server:
  port: 9007
spring:
  application:
    name: tensquare_search
  data:
    elasticsearch:
      cluster-nodes: 192.168.43.210:9300
      cluster-name: docker-cluster
  rabbitmq:
    host: 192.168.43.210
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true